### ISSUE TITLE
gradle 

### ISSUE THREAD

**Issue by jjhesk** [HendrixString/Android-PdfMyXml#1]
is this possible to upload ur file to jcenter or bintray?

**Comment by HendrixString** [comment]
Hi i will look into it.
Also i need to publish an aar on github

**Comment by se-bastiaan** [comment]
It's possible to do this using jitpack.io if you do not want to go through the whole jcenter/maven central process. I did it for my own usage in https://github.com/se-bastiaan/Android-PdfMyXml. The docs are also really simple: https://jitpack.io/docs/ANDROID/

**Comment by HendrixString** [comment]
Ok. Thanks. We will work out something.
