### ISSUE TITLE
add an API to add a list of pages for print

### ISSUE THREAD

**Issue by ahmadalibaloch** [HendrixString/Android-PdfMyXml#11]
The API provided can be used only if we have predefined pages, say I want to add two pages then I would do this:
`new PdfDocument.Builder(context).addPage(page1).addPage(page2)`
but what if I want to generate pages with code, for example, to print 3 pages of a quotation because the product list is dynamically selected by a user. Then I would need an api like this.
`new PdfDocument.Builder(context).addPages(pagesList)`

**Comment by HendrixString** [comment]
Hi. 
Two options.
1. Don't use the builder. The readme shows example of how to do it without the builder 
1. Contribute And make a pull request

Thanks
Tomer
