### ISSUE TITLE
It takes too long when pages is added on the pdf

### ISSUE THREAD

**Issue by Ric17101** [HendrixString/Android-PdfMyXml#12]
It takes 1 mins. to produce the PDF... Is it possible to minimize the time or speed up the file generation?  I tried this line on my Manifest but same result. Thank you!
```
<application
android:hardwareAccelerated="true" 
...
/>
```

**Comment by HendrixString** [comment]
Hi
Yes it does take long on some devices.
I believe the thread has very high priority.
Compiling a PDF is an intensive task

**Comment by Ric17101** [comment]
Okie, Thank you for your response... I will just try to implement the pdf on the backend as an option...
