### ISSUE TITLE
Bold text

### ISSUE THREAD

**Issue by FelipePedrotiRaymundo** [HendrixString/Android-PdfMyXml#14]
I followed the README sample, but bold text isn't working. There are other manner to do this?

**Comment by HendrixString** [comment]
Hi,
Post your code

**Comment by FelipePedrotiRaymundo** [comment]
Sorry for bothering you, I just found the problem. I'm using calligraphy library from @chrisjenx, and it injects a LayoutInflater in application level. The injected font doesn't have bold in it, but if I inject the bold font in the XML TextView, the PDF printed assumes it. 

It's good to know that I can have custom typefaces on generated PDF like this.
