### ISSUE TITLE
remove some view 

### ISSUE THREAD

**Issue by tank777** [HendrixString/Android-PdfMyXml#15]
#how to remove some view from the layout?

**Comment by HendrixString** [comment]
What do you mean?

**Comment by tank777** [comment]
if I have the button in layout and I don't want in pdf file.

**Comment by HendrixString** [comment]
AbstractViewRenderer.initView(View view)

This is your chance to get the inflated view
and do something like

view.findViewById(button_id).setVisibility(false)
