### ISSUE TITLE
How do i Convert my view if i used databinding in it. ?

### ISSUE THREAD

**Issue by DhiralKaniya** [HendrixString/Android-PdfMyXml#16]
I have created view with the concept of Databinding. Now i want to convert that view in PDF with the help of your lib. 

it is giving me error like 
`    Process: com.example.the_king.apartmentmanagementsystem, PID: 18215
                                                                                                    java.lang.IllegalStateException: 
    DataBinding  
    must be created in view's UI Thread 
`
is it possible to convert my databinding view in to pdf with the help of your library ?

**Comment by HendrixString** [comment]
Try setting the flag
inflateOnMainThread inside the PdfDocument class.
This flag or a similar variant inflates the view on a background or main thread, try playing with it.

Report your findings.

All the best,
Tomer
