### ISSUE TITLE
How to set data in AbstractViewRenderer?

### ISSUE THREAD

**Issue by RaziaSandhu** [HendrixString/Android-PdfMyXml#17]
Hello

I have an error in AbstractViewRenderer initView() on check1.setChecked(true).Also it does not let me use Picasso.  Please help me.

android.util.AndroidRuntimeException: Animators may only be run on Looper threads

My Code:

public class SignOutActivity extends AppCompatActivity implements View.OnClickListener {
    ImageView ivback;
    Button btn_save_form;
    TextView header_text;
    EditText edt_name;
    CheckBox check1;
    private String _text = "Razia";
    ImageView image1;
    boolean checked = true;
    String image_path;
    AbstractViewRenderer page;
    public Handler mHandler;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_sign_out);
        header_text = (TextView) findViewById(R.id.header_text);
        ivback = (ImageView) findViewById(R.id.ivback);
        image1 = (ImageView) findViewById(R.id.image1);
        btn_save_form = (Button) findViewById(R.id.btn_save_form);
        check1 = (CheckBox) findViewById(R.id.check1);
        edt_name = (EditText) findViewById(R.id.edt_name);

        btn_save_form.setOnClickListener(this);
        ivback.setOnClickListener(this);
        image1.setOnClickListener(this);

    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {

            case R.id.ivback:
                finish();
                break;

            case R.id.image1:
                Intent intent = new Intent(this, SigningActivity.class);
                startActivityForResult(intent, 100);
                break;

            case R.id.btn_save_form:
                ivback.setVisibility(View.GONE);
                btn_save_form.setVisibility(View.GONE);

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                    makePdf();

                }
                break;
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // check if the request code is same as what is passed  here it is 2
        if (requestCode == 100) {
            image_path = data.getStringExtra("path");
            Picasso.with(getApplicationContext()).load(new File(image_path)).fit().into(image1);
        }
    }

    @RequiresApi(api = Build.VERSION_CODES.KITKAT)
    void makePdf() {
        page = new AbstractViewRenderer(SignOutActivity.this, R.layout.activity_sign_out) {
            CheckBox check1;

            @Override
            protected void initView(View view) {
                check1 = (CheckBox) view.findViewById(R.id.check1);
                edt_name = (EditText) view.findViewById(R.id.edt_name);
                header_text = (TextView) findViewById(R.id.header_text);
                ivback = (ImageView) view.findViewById(R.id.ivback);
                image1 = (ImageView) view.findViewById(R.id.image1);
                btn_save_form = (Button) view.findViewById(R.id.btn_save_form);

                ivback.setVisibility(View.GONE);
                btn_save_form.setVisibility(View.GONE);

                image1.setImageURI(Uri.parse(image_path));
                edt_name.setText(_text);
                //   Picasso.with(SignOutActivity.this).load(new File(image_path)).fit().into(image1);

                check1.setChecked(checked);

            }
        };
        page.setReuseBitmap(true);

        new PdfDocument.Builder(getApplicationContext()).addPage(page).filename("test12").orientation(PdfDocument.A4_MODE.PORTRAIT)
                .progressMessage(R.string.app_name).progressTitle(R.string.app_name).renderWidth(1480).renderHeight(2508)
                .listener(new PdfDocument.Callback() {
                    @Override
                    public void onComplete(File file) {
                        ivback.setVisibility(View.VISIBLE);
                        header_text.setGravity(Gravity.CENTER);
                        btn_save_form.setVisibility(View.VISIBLE);
                        Log.e(PdfDocument.TAG_PDF_MY_XML, "Complete   " + file.getAbsolutePath());
                    }

                    @Override
                    public void onError(Exception e) {
                        ivback.setVisibility(View.VISIBLE);
                        header_text.setGravity(Gravity.LEFT);
                        btn_save_form.setVisibility(View.VISIBLE);
                        Log.e(PdfDocument.TAG_PDF_MY_XML, "Error");
                    }
                }).create().createPdf(this);
    }
}

**Comment by HendrixString** [comment]
Try
.setInflateOnMainThread(true)

**Comment by RaziaSandhu** [comment]
got window leaked error on createPdf() when using   .setInflateOnMainThread(true)

**Comment by RaziaSandhu** [comment]
Is it possible to create pdf without initialize views in  AbstractViewRenderer initView() ?

**Comment by HendrixString** [comment]
Did the error crashed your app?
You probably got it from the loader dialog.
I think u can do it outside, look at the renderers implementations. That would defeat the purpose though
