### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by se-bastiaan** [HendrixString/Android-PdfMyXml#2]
I started using this library three days ago and I noticed some parts in the library that I thought could be improved. And features that weren't really necessary. So I changed them and basically made our own version. Since this is an open source project I would like to discuss them and see if the changes would be candidates for merges into the library.
- The `PdfDocument` has a `Builder`, but it is possible to change it's fields after the creation. When a `Builder` is provided I would assume that the instance itself is immutable (which I think is a good idea). That thus means that you create a `PdfDocument` using the `Builder` and then the only thing you can do using the `PdfDocument` is adding new pages (which you then can't do in the builder). Was there any specific reason to do it differently? What do you think about changing this behaviour?
  - I noticed that the `Builder` has a `context(Context)`method, but wouldn't it be easier to provide the `Context` via the constructor? You can't use the `PdfDocument` without it.
- The `Callback` in the `PdfDocument` does provide an `onError` call but it does not give back the Exception that occurred, moreover: it does not give any feedback about what happened at all. Wouldn't it be better to pass all possible exceptions that can occur via the `Callback`?
- The library current provides a loading dialog for when the PDF is being created. It's attached when `createPdf(Context)` is called, using another `Context` (probably also the one which was provided before). It can come in handy, but it is probably not this library's task to do this. Any developer can then show his/her own dialog or screen before calling `createPdf` and hide it again after receiving a response using the listener. Plus: You'd rather want a DialogFragment since it handles the lifecycle of the Dialog and prevents Dialog leakage.
- I wanted to save my PDF files in a specific directory, but this is not possible. Adding a directory parameter would solve this and improve the flexibility.
  - https://github.com/HendrixString/Android-PdfMyXml/blob/master/src/main/java/com/hendrix/pdfmyxml/PdfDocument.java#L349 creates the save directory. I think this shouldn't happen here but outside the library, let the user handle the file system so that you do not make implicit choices for him/her. Just throw an exception when the save directory does not exist.

**Comment by HendrixString** [comment]
Hi Sebastian. I will look into it tomorrow. Pull requests will be great, but let me go through the suggestions so I can comment on these potential candidates.

Thanks

**Comment by se-bastiaan** [comment]
:+1:

**Comment by HendrixString** [comment]
@se-bastiaan 
hi Sebastian.
sorry for the long delay
and thank you very much for the good suggestions.

1) the object will remain sem-immutable currently, but the `context` should go in the constructor, so feel free to pull request on that
2) the `Callback` should provide error message, pull request on that as well
3) agreed, but, there should be a flag indicating if to cancel or keep this behaviour.
you can PR with a flag that can cancel this dialog if the user wishes.
4) currently, there is a `File` object, and you want a directory instead? can u please tell me more about that?

dont forget to update the documenation

all the best
Tomer

**Comment by se-bastiaan** [comment]
1) :+1: 
2) :+1: 
3) :+1: 
4)
Currently it is only possible to provide a filename and the used directory is `_ctx.getExternalFilesDir(null) + File.separator + "pdfdroid"`. I would like to provide my own `File` object that should be used as the location of the pdf.

**Comment by HendrixString** [comment]
I see. Ok, so PR on that please

Thanks

**Comment by HendrixString** [comment]
@se-bastiaan I merged the pull requests.
can you please compile a release `aar` and send it to me. 
also put `jitpack` in the documentation with instructions.
I will add your credit in the readme file as contributor.

thank you very much.

**Comment by se-bastiaan** [comment]
@HendrixString Sure. For Jitpack I have to change the folder structure of the repository root.

**Comment by se-bastiaan** [comment]
The AAR: http://cl.ly/fZrA
