### ISSUE TITLE
Gradle build failure

### ISSUE THREAD

**Issue by anitaa1990** [HendrixString/Android-PdfMyXml#20]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index 66201 into a non-jumbo instruction!

Any help?

**Comment by anitaa1990** [comment]
I fixed this with multiDexEnabled true but I wanted to know why this was happening? And if there was any way to reduce the number of classes/methods in the jar?

**Comment by HendrixString** [comment]
Maybe proguard
