### ISSUE TITLE
Eternal loader when createPdf was called

### ISSUE THREAD

**Issue by andriizhumela** [HendrixString/Android-PdfMyXml#21]
Hi there.
I try to use your library Android-PdfMyXml, but i got eternal loader when createPdf was called.
I have no error or warning and i tryed use PdfDocument (and PdfDocument.Builder too)
Maybee you can give me advise some solution? I will wery grateful for your help.

My code:
`    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        /*PDFPage pdfPage = new PDFPage(this);
        pdfPage.setLogo(R.mipmap.ic_launcher);
        pdfPage.setTitle(R.string.app_name);
        pdfPage.setText(R.string.text_fish);
        pdfPage.makePdf("file.pdf");*/

        _title = getString(R.string.app_name);
        _text = getString(R.string.text_fish);
        _logo = R.mipmap.ic_launcher;
        makePdf();

        Toast.makeText(this, "PDF File created", Toast.LENGTH_SHORT);
    }

    public void makePdf() {
        AbstractViewRenderer page = new AbstractViewRenderer(this, R.layout.page_pdf) {

            @Override
            protected void initView(View view) {
                TextView title = (TextView) view.findViewById(R.id.tvTitle);
                TextView message = (TextView) view.findViewById(R.id.tvMessage);
                ImageView ivLogo = (ImageView) view.findViewById(R.id.ivLogo);

                title.setText(_title);
                message.setText(_text);
                ivLogo.setImageResource(_logo);
            }
        };
        page.setReuseBitmap(true);

        new PdfDocument.Builder(this).addPage(page).filename("test")
                .orientation(PdfDocument.A4_MODE.PORTRAIT)
                .progressMessage(R.string.app_name)
                .progressTitle(R.string.app_name)
                .renderWidth(1480).renderHeight(2500)
                .listener(new PdfDocument.Callback() {
                    @Override
                    public void onComplete(File file) {
                        Log.i(PdfDocument.TAG_PDF_MY_XML, "Complete");
                    }

                    @Override
                    public void onError(Exception e) {
                        Log.i(PdfDocument.TAG_PDF_MY_XML, "Error");
                    }
                })
                .create()
                .createPdf(this);

        /*PdfDocument doc = new PdfDocument(this);
        doc.setContext(this);
        doc.addPage(page);

        doc.setRenderWidth(1480);
        doc.setRenderHeight(2500);
        doc.setOrientation(PdfDocument.A4_MODE.PORTRAIT);
        doc.setFileName(filename);
        doc.setInflateOnMainThread(false);
        doc.setListener(new PdfDocument.Callback() {
            @Override
            public void onComplete(File file) {
                Log.d(this.getClass().getSimpleName(), "Complete");
            }

            @Override
            public void onError(Exception e) {
                Log.d(this.getClass().getSimpleName(), "Error");
            }
        });

        doc.createPdf(this);*/
    }`

**Comment by HendrixString** [comment]
Can u please explain to me what is eternal loader? What do u mean by that?

**Comment by andriizhumela** [comment]
It's a alert dialog with loader but this doesn't matter for now.
Finally i just waited several minutes (8 minutes for simple document with text) and file was created. But it too long.
Maybe you can give me advice, how i can make faster this process?

**Comment by HendrixString** [comment]
The thread that is creating the PDF is given the highest priority. Can u confirm this issue is reproduced on more devices?
