### ISSUE TITLE
Webview issues

### ISSUE THREAD

**Issue by xjdeath** [HendrixString/Android-PdfMyXml#26]
Hi,  i'm traying to  load a webview so i can print a web page but it gets me the following error
"A WebView method was called on thread ''. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads."
Any idea on how to implement the webview?

**Comment by HendrixString** [comment]
Use . setInflateOnMainThread(true)

**Comment by xjdeath** [comment]
i use . setInflateOnMainThread(true), but the page does not load in the webview, the output is just white. Edit: Any suggestions?

**Comment by HendrixString** [comment]
Web views are asynchronous.
So you probably snapshot the view 
before it was fully rendered.
Try to implement a view renderer that
listens to such event from the web view
