### ISSUE TITLE
Not geting the full view in pdf

### ISSUE THREAD

**Issue by sparkOverfl0w** [HendrixString/Android-PdfMyXml#27]
The issue im facing  is that i have a **ScrollView** , whenever the **pdf** is generating only the visible part of the **ScrollView** is showing in the **pdf** and rest of the part is not showing.  I want to generate another **page** in the pdf and show the rest part of my **ScrollView** on that page. **Please help me asap** :( stucked in this from last two days

**Comment by HendrixString** [comment]
Hi.

Using scroll view is not a good strategy
because it is clipped against itself.
Simply don't use one.
This library does not support continuous
rendering. Sorry.

Simply get everything outside.

**Comment by sparkOverfl0w** [comment]
So you are saying there is no way by which i can render the rest part in another page of the pdf? :(

**Comment by HendrixString** [comment]
You cannot with scrollView.

**Comment by sparkOverfl0w** [comment]
Okay then , please suggest any other way :(

**Comment by HendrixString** [comment]
move the content of the Srollview outside and divide it into pages, that's it,
the dimensions have to be static

**Comment by sparkOverfl0w** [comment]
one final question , if i dont use any scrollview how i can be able to show the  stuff in my app which does not fit in the display, Actually im developing an app to make Resume , So i dont want  to fit all the details in the display as it will look terribly small,So in order to see the whole stuff user have to scroll down to see,

**Comment by sparkOverfl0w** [comment]
https://i.imgur.com/HhlrEvI_d.jpg?maxwidth=640&shape=thumb&fidelity=medium

please see this , i want to get the stuffs like this in my pdf ,

**Comment by HendrixString** [comment]
The API of this library supports multi pages.
You need design each page. Or to break your 
Long content into pages. The way most do it,
is to break the pages into seperate template views.
Another option might be using a scrollView and taking snapshots, and scrolling the view and then taking another snapshot etc...
I think this is possible by using the scrollTo() API of a scrollView.

Another option is to make template containers.
And to calculate how many of them you would need and then to add them dynamically

**Comment by HendrixString** [comment]
something like the code below, and then your templates/pages
are just ImageViews, that you feed them the images

```java
@Override
    public final Bitmap render(Bitmap bitmap, int width, int height, in page_index, ScrollView view) {
        int specWidth   = View.MeasureSpec.makeMeasureSpec(width,  width==0   ? View.MeasureSpec.UNSPECIFIED : View.MeasureSpec.EXACTLY);
        int specHeight  = View.MeasureSpec.makeMeasureSpec(height, height==0  ? View.MeasureSpec.UNSPECIFIED : View.MeasureSpec.EXACTLY);

        view.measure(specWidth, specHeight);

        view.layout(0, 0, view.getMeasuredWidth(), view.getMeasuredHeight());

        // recycle bitmap
        Bitmap b        = bitmap;//Bitmap.createBitmap(view.getWidth(), view.getHeight(), Bitmap.Config.ARGB_8888);

        Canvas c        = new Canvas(b);
       
        //// here scroll
        view.scrollTo(0, PIXELS_PER_PAGE * page_index);

        view.draw(c);

        return  b;
    }
```

**Comment by sparkOverfl0w** [comment]
okay thanks dude , will try this.out ,

**Comment by developerfromjokela** [comment]
This functionality should be out of the box, not as separate. Now this library is pretty useless...
