### ISSUE TITLE
Creating pdf with multipages dynamically

### ISSUE THREAD

**Issue by sparkOverfl0w** [HendrixString/Android-PdfMyXml#30]
Can you please post a code sniffet on how to create a pdf with multiple.pages dynamically , i mean if someone has a scrollview than how he/she will be able to get the whole long content in the pdf devided in devided in multiple pages , Thanks

**Comment by murwa** [comment]
@sparkOverfl0w did you find any solution?

**Comment by sparkOverfl0w** [comment]
nope , you have to break the pages statically

**Comment by ahmadbilalctech** [comment]
@sparkOverfl0w can you share the code?

**Comment by aeiou-st** [comment]
please share the code buddy. we are still facing the issue in 2023

**Comment by HendrixString** [comment]
Hi guys,

There is no concept of flow with views like in HTML.

I suggest you break the view statically with some math calculation and then add dynamically more views with a window of items.
