### ISSUE TITLE
PDF checkbox is not checked.

### ISSUE THREAD

**Issue by gomezjc** [HendrixString/Android-PdfMyXml#32]
Hello, i'm trying to print a checkbox but this is not checked when the pdf is generated.

in the layout
![captura de pantalla 2018-05-31 a la s 9 31 09 p m](https://user-images.githubusercontent.com/11074913/40817914-3bd35168-651a-11e8-9176-206952b23271.png)

in the PDF
![captura de pantalla 2018-05-31 a la s 9 31 19 p m](https://user-images.githubusercontent.com/11074913/40817921-481129fa-651a-11e8-8542-9cfe68c5ead3.png)

there's any solution for this?

thank you! 👍

**Comment by HendrixString** [comment]
Show me the piece of code that generates this please

**Comment by sourav-khunger** [comment]
I'm also not getting the updated view

**Comment by HendrixString** [comment]
this is an Android bug.
after you check the checkbox, you need to force
invalidation on the view. try using one of the invalidation
calls of the view. if it is invalidated, then next call to draw
should draw the correct state. also, make sure inflateOnMainThread is true
if I recall
