### ISSUE TITLE
The pdf creation process does not work in the DEGUB Build Variant

### ISSUE THREAD

**Issue by SalvatoreAD** [HendrixString/Android-PdfMyXml#37]
Hi, I noticed that if on Android Studio set Build Variant to DEBUG the process of creating the pdf is slow and does not work.

When I set Build Variant to RELEASE seems to work well

**Comment by HendrixString** [comment]
@SalvatoreAD hi

can you give more information ?
does it wait forever ? does it finish at some point ?

**Comment by SalvatoreAD** [comment]
@HendrixString hi, 

To create the pdf use this function

 ```
PdfDocument doc = new PdfDocument(thisContext);
        doc.addPage(immagine_pdf);

        doc.setRenderWidth(PDF_WIDTH);
        doc.setRenderHeight(PDF_HEIGHT);
        doc.setOrientation(PdfDocument.A4_MODE.PORTRAIT);
        doc.setProgressTitle(R.string.app_name);
        doc.setProgressMessage(R.string.close_pdf);
        doc.setFileName(nomeFile);
        doc.setSaveDirectory(new File(pathFileFirma));
        doc.setInflateOnMainThread(true);
        doc.setListener(new PdfDocument.Callback() {
            @Override
            public void onComplete(File file) {
                Log.i(PdfDocument.TAG_PDF_MY_XML, "Complete");
            }

            @Override
            public void onError(Exception e) {
                log.log(Level.SEVERE, e.getLocalizedMessage());
                Crashlytics.logException(e);
            }
    });
```

If I start the app in release mode, it works fine, if I start it in debug mode, it never fails to get to the function 'onComplete'.

**Comment by HendrixString** [comment]
@SalvatoreAD 

can you try also implement the onError callback of the interface and see if it gets invoked ?

thanks

**Comment by SalvatoreAD** [comment]
Sorry, I have the 'onError' function, but no error appears. I'll do tests these days and update you.
