### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by ionicsolve** [HendrixString/Android-PdfMyXml#38]
this error occurs when generate pdf from view.     I also tried runonuithread, new Handler(Looper.mainLooper) with runnable, but now work anything

**Comment by HendrixString** [comment]
@ionicsolve basically, only the main thread should inflate views and touch them,
thread safety for UI is not guaranteed in Android.
BUT, in this  lib, there is a flag `inflateOnMainThread` or something like that,
use it
