### ISSUE TITLE
Problem with implementation

### ISSUE THREAD

**Issue by franquicidad** [HendrixString/Android-PdfMyXml#39]
Hello @HendrixString hendrix thank you for this library, looking forward on doing donations if things go as expected. I try to add to dependencies but it doesnt compile.

![Captura de Pantalla 2020-06-24 a la(s) 12 42 57 p  m](https://user-images.githubusercontent.com/28768991/85605953-487f6400-b618-11ea-8d34-b6b06049cdec.png)

**Comment by HendrixString** [comment]
@franquicidad try 1.0.8
